### PR TITLE
XWIKI-13478: On Homepage, replace Dashboard include with content

### PR DESCRIPTION
**Pull request by evalica**
- Replacing the Dashboard include with help content
- Adding a SSX to style the used table

### CODE REVIEW

**Comment by vmassol** [comment]
Note that the SSX is not that good since the user is supposed to be able to customize that page and the SSX will remain ;)

**Comment by evalica** [comment]
I've used tables in order to have some layout inside the page. 
The SSX removed the table border and margins, so the changes will not be very big. 

Now, the ssx could be removed by the admin that changes the Homepage content.

Alternatively I could have used the {{container}} macro. Unfortunately, the user would need to go through the editor's macro section in order to edit the section's content. That's why I preferred tables (but these come with some styling). Using inline styling (instead of SSX) would make the syntax more scary. 

So I don't know an alternative to that SSX.

**Comment by vmassol** [comment]
"Now, the ssx could be removed by the admin that changes the Homepage content.". That won't happen it's too technical. If the admin was able to do this we wouldn't have needed to modify the home page content at all ;)

It's not a big deal, it just means the SSX will stay and it'll probably have no effect. I haven't looked at it; we just need to make sure it's not going to affect any content the user will put on the home page.

An alternative is also to move this SSX to another hidden page so that the home page stays "clean".

**Comment by evalica** [comment]
If we were to move it, we will need velocity in order to include it. Now we rely on "Use this extension: on this page ..." option.

**Comment by evalica** [comment]
TODO: 
- [ ] Reach a conclusion on layout
- [ ] XWiki.XWikiPreferences changes with the panels
- [ ] Remove the translation key from Title
- [ ] Add Main.WebHome in the Translations release script

**Pull request merged**
