### PR TITLE
Fixes DocExtra in OfficeImporter (XWIKI-16498)

### PR DESCRIPTION
**Pull request by Haxsen**
XWIKI-16498: Remove docextra from OfficeImporter action-result pages
Link : https://jira.xwiki.org/browse/XWIKI-16498
(Let me know my mistakes) - Haxsen

### CODE REVIEW

**Comment by vmassol** [comment]
Hi. Thanks for the PR! Could you provide a screenshot of executing XWiki with this change, to verify it works?

**Comment by vmassol** [comment]
Small detail: please follow the defined format for the commit comment:

"XWIKI-16498: Remove docextra from OfficeImporter action-result pages"

See https://dev.xwiki.org/xwiki/bin/view/Community/DevelopmentPractices#HRule:AlwaysputaJIRAissuereferenceincommitmessages

Thanks!

**Comment by Haxsen** [comment]
Hi Vincent, Give me some time to provide a screenshot, and apologies for not knowing JIRA issue referencing.
Thanks for letting me know!

**Comment by Haxsen** [comment]
Sorry! This doesn't solve the issue. Closing this PR and creating a new one with actual solution.

**Comment by vmassol** [comment]
> Sorry! This doesn't solve the issue. Closing this PR and creating a new one with actual solution.

Yes that was my guess and why I asked for a screenshot :)

**Comment by Haxsen** [comment]
It did solve the issue but my testing was wrong haha.. that time I was just panicking, so my apologies :p

**Pull request closed without merging**
