### PR TITLE
XWIKI-21044: Remove refactoring.rename.useAtomicRename property and related code

### PR DESCRIPTION
**Pull request by surli**
* Remove the property from xwiki.properties.vm and the only usage of it in XWiki.java
  * Move all deprecated APIs that are no longer used to legacy

### CODE REVIEW

**Comment by surli** [comment]
For me the work is done but opening a PR because I'm obtaining this report from revapi when building legacy-oldcore: 
```
<item>
  <ignore>true</ignore>
  <code>java.annotation.attributeRemoved</code>
  <old>method void com.xpn.xwiki.doc.XWikiDocument::rename(org.xwiki.model.reference.DocumentReference, com.xpn.xwiki.XWikiContext) throws com.xpn.xwiki.XWikiException @ com.xpn.xwiki.doc.LazyXWikiDocument</old>
  <new>method void com.xpn.xwiki.doc.XWikiDocument::rename(org.xwiki.model.reference.DocumentReference, com.xpn.xwiki.XWikiContext) throws com.xpn.xwiki.XWikiException @ com.xpn.xwiki.doc.LazyXWikiDocument</new>
  <annotation>@java.lang.Deprecated</annotation>
  <attribute>since</attribute>
  <justification>ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE</justification>
</item>
<item>
  <ignore>true</ignore>
  <code>java.annotation.attributeRemoved</code>
  <old>method void com.xpn.xwiki.doc.XWikiDocument::rename(org.xwiki.model.reference.DocumentReference, java.util.List&lt;org.xwiki.model.reference.DocumentReference&gt;, com.xpn.xwiki.XWikiContext) throws com.xpn.xwiki.XWikiException @ com.xpn.xwiki.doc.LazyXWikiDocument</old>
  <new>method void com.xpn.xwiki.doc.XWikiDocument::rename(org.xwiki.model.reference.DocumentReference, java.util.List&lt;org.xwiki.model.reference.DocumentReference&gt;, com.xpn.xwiki.XWikiContext) throws com.xpn.xwiki.XWikiException @ com.xpn.xwiki.doc.LazyXWikiDocument</new>
  <annotation>@java.lang.Deprecated</annotation>
  <attribute>since</attribute>
  <justification>ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE</justification>
</item>
<item>
  <ignore>true</ignore>
  <code>java.annotation.attributeRemoved</code>
  <old>method void com.xpn.xwiki.doc.XWikiDocument::rename(org.xwiki.model.reference.DocumentReference, java.util.List&lt;org.xwiki.model.reference.DocumentReference&gt;, java.util.List&lt;org.xwiki.model.reference.DocumentReference&gt;, com.xpn.xwiki.XWikiContext) throws com.xpn.xwiki.XWikiException @ com.xpn.xwiki.doc.LazyXWikiDocument</old>
  <new>method void com.xpn.xwiki.doc.XWikiDocument::rename(org.xwiki.model.reference.DocumentReference, java.util.List&lt;org.xwiki.model.reference.DocumentReference&gt;, java.util.List&lt;org.xwiki.model.reference.DocumentReference&gt;, com.xpn.xwiki.XWikiContext) throws com.xpn.xwiki.XWikiException @ com.xpn.xwiki.doc.LazyXWikiDocument</new>
  <annotation>@java.lang.Deprecated</annotation>
  <attribute>since</attribute>
  <justification>ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE</justification>
</item>
<item>
  <ignore>true</ignore>
  <code>java.annotation.attributeRemoved</code>
  <old>method void com.xpn.xwiki.doc.XWikiDocument::rename(org.xwiki.model.reference.DocumentReference, com.xpn.xwiki.XWikiContext) throws com.xpn.xwiki.XWikiException</old>
  <new>method void com.xpn.xwiki.doc.XWikiDocument::rename(org.xwiki.model.reference.DocumentReference, com.xpn.xwiki.XWikiContext) throws com.xpn.xwiki.XWikiException</new>
  <annotation>@java.lang.Deprecated</annotation>
  <attribute>since</attribute>
  <justification>ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE</justification>
</item>
<item>
  <ignore>true</ignore>
  <code>java.annotation.attributeRemoved</code>
  <old>method void com.xpn.xwiki.doc.XWikiDocument::rename(org.xwiki.model.reference.DocumentReference, java.util.List&lt;org.xwiki.model.reference.DocumentReference&gt;, com.xpn.xwiki.XWikiContext) throws com.xpn.xwiki.XWikiException</old>
  <new>method void com.xpn.xwiki.doc.XWikiDocument::rename(org.xwiki.model.reference.DocumentReference, java.util.List&lt;org.xwiki.model.reference.DocumentReference&gt;, com.xpn.xwiki.XWikiContext) throws com.xpn.xwiki.XWikiException</new>
  <annotation>@java.lang.Deprecated</annotation>
  <attribute>since</attribute>
  <justification>ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE</justification>
</item>
<item>
  <ignore>true</ignore>
  <code>java.annotation.attributeRemoved</code>
  <old>method void com.xpn.xwiki.doc.XWikiDocument::rename(org.xwiki.model.reference.DocumentReference, java.util.List&lt;org.xwiki.model.reference.DocumentReference&gt;, java.util.List&lt;org.xwiki.model.reference.DocumentReference&gt;, com.xpn.xwiki.XWikiContext) throws com.xpn.xwiki.XWikiException</old>
  <new>method void com.xpn.xwiki.doc.XWikiDocument::rename(org.xwiki.model.reference.DocumentReference, java.util.List&lt;org.xwiki.model.reference.DocumentReference&gt;, java.util.List&lt;org.xwiki.model.reference.DocumentReference&gt;, com.xpn.xwiki.XWikiContext) throws com.xpn.xwiki.XWikiException</new>
  <annotation>@java.lang.Deprecated</annotation>
  <attribute>since</attribute>
  <justification>ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE</justification>
</item>
```

I don't understand why as I kept the whole deprecated annotations...

**Comment by vmassol** [comment]
I don't know what's the problem but you could check the generated code after the aspectj weaving (you can find the weaved classes in the target directory). Maybe the bytecode doesn't contain the since.

**Comment by surli** [comment]
> Maybe the bytecode doesn't contain the since.

Yes I confirm it doesn't contain it.

**Comment by vmassol** [comment]
So that could be a bug/limitation in aspectj or maybe the java compiler doesn't keep the since in the bytecode (easy to verify).

**Comment by vmassol** [comment]
Note that we use aspectj 1.9.7 which seems to be the most recent version.

**Pull request merged**
