### PR TITLE
XWIKI-15719: .notifications-toggles inputs are missing labels

### PR DESCRIPTION
**Pull request by atallahade**
## Jira

https://jira.xwiki.org/browse/XWIKI-15719

## Change

* Add missing titles to inputs.

## Note

This approach was used: https://www.w3.org/WAI/tutorials/forms/labels/#using-the-title-attribute

### CODE REVIEW

**Comment by evalica** [comment]
The issue is not about adding titles (those are good too), but adding **labels**, see 
* https://webaim.org/techniques/forms/controls#checkbox 
* https://www.xwiki.org/xwiki/bin/view/Documentation/DevGuide/FrontendResources/VerticalForms/ 
and we have some examples in Administration for checkboxes, etc.

**Comment by evalica** [comment]
Since we don't want the labels be displayed for the graphical end-user, but we want them for accessibility reasons, we need to add classes like `.sr-only` or `.hidden`, see https://getbootstrap.com/docs/3.3/css/#helper-classes-show-hide

**Comment by atallahade** [comment]
@evalica I've used labels instead of title as I don't think we need both.

**Comment by evalica** [comment]
A. Spacing between the controls gets a bit different comparing to the old version.
B. Since there is repetitive code, maybe we could have a macro or have a for to remove duplication?

Besides this, looking good.

**Comment by atallahade** [comment]
@evalica:
> A. Spacing between the controls gets a bit different comparing to the old version.

Yes it's more clear that way. I've added comments at the end of the lines to avoid new lines between the inputs.

> B. Since there is repetitive code, maybe we could have a macro or have a for to remove duplication?

I'll define a macro to make the code clean.

**Pull request merged**
