### PR TITLE
XWIKI-17628: Dropdowns are displayed inside #xwikimainmenu

### PR DESCRIPTION
**Pull request by evalica**
- Replace the custom embedded display by having the dropdown outside the nav.
- Reset overwritten properties with Bootstrap variables.

### CODE REVIEW

**Comment by evalica** [comment]
Before
before_open

After
after_open

**Comment by surli** [comment]
Thanks Caty!

**Comment by evalica** [comment]
Thank you Simon!

**Comment by vmassol** [comment]
Hey, hi @evalica ! Thanks for this (you're keeping your active committer status, lol ? :)). Hope you're doing good.

**Pull request merged**
