### PR TITLE
XWIKI-21914: Inconsistency of icons for "delete" and "close" actions

### PR DESCRIPTION
**Pull request by tkrieck**
# Jira URL

https://jira.xwiki.org/browse/XWIKI-21914

# Changes

## Description

* This PR changes some icons named `"cross"` icons to `"trash"` 

## Clarifications

* Only icons dealing with deleting actions will be changed
* Actions like such as close or cancel will remain as a cross.
* Discussions in: https://forum.xwiki.org/t/inconsistency-of-actions-vs-icons/14162

# Screenshots & Video

Screenshot 2024-05-06 at 11 17 50

Screenshot 2024-05-06 at 11 16 19

# Executed Tests

-

# Expected merging strategy

* Prefers squash: Yes 
* Backport on branches:
  *

### CODE REVIEW

**Comment by surli** [comment]
@tkrieck the changes look good but it actually might impact some integration tests: we do use some UI elements for those. Might be great if you could run integration tests on `xwiki-platform-flamingo-skin-test-docker` after building with your changes.

**Comment by tkrieck** [comment]
> @tkrieck the changes look good but it actually might impact some integration tests: we do use some UI elements for those. Might be great if you could run integration tests on `xwiki-platform-flamingo-skin-test-docker` after building with your changes.

Ok, but I am not familiar with these tests, if it's not much trouble, can you point me to some documentation on them?

**Comment by Sereza7** [comment]
@tkrieck 

> Ok, but I am not familiar with these tests, if it's not much trouble, can you point me to some documentation on them?

https://dev.xwiki.org/xwiki/bin/view/Community/Testing/DockerTesting/

It's a bit much to get through at first. Here is how I'd have tested it.
1. Build your changes: you pick all the modules where you have made changes, and you build them again. 
1.1 List modules
* `xwiki-platform-flamingo-skin-resources`
* `xwiki-platform-index-ui`
* `xwiki-platform-livedata-api`
* `xwiki-platform-web-templates`
1.2. Make sure your command prompt is at the root of the maven project (should be there by default with the intellij idea integrated terminal)
1.3. Build each of them with a command similar to `mvn clean install -f xwiki-platform-core/xwiki-platform-flamingo/xwiki-pllatform-flamingo-skin/xwiki-platform-flamingo-skin-resources` (there's probably options to make that command shorter and more optimal~~)
2. Start the tests Simon recommended with a command like `mvn clean install -f xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-test-docker -Pdocker` (you can even add wcag validation with the parameter `-Dxwiki.test.ui.wcag=true` :)) )

The tests should take a while, they will start their own instance of XWiki. If the build passes (everything is green at the end, opposite to failing where you see a lot of red), you're all good! The tricky part later on is to find what tests to pass (ideally we'd check all of them, but it takes a long computation time and we can't do that, so you need to find the ones most relevant to your changes).

**Comment by tkrieck** [comment]
Using:
`mvn clean install -f xwiki-platform-core/xwiki-platform-flamingo/xwiki-pllatform-flamingo-skin/xwiki-platform-flamingo-skin-resources`

Gave me this error, however, it is also happening in the master branch. So I think it is not because of my changes
`[ERROR] Failures:
[ERROR]   AllIT$NestedObjectEditorIT>ObjectEditorIT.preventUsersToLeaveTheEditorWithoutSaving:113 A confirm alert should be triggered
[ERROR] Errors:
[ERROR]   AllIT$NestedEditIT>EditIT.saveAndFormManipulation:269 » Timeout Expected condition failed: waiting for org.xwiki.test.ui.XWikiWebDriver$$Lambda/0x0000000501bffd28@23567b98 (tried for 10 second(s) with 500 milliseconds interval)
Build info: version: '4.20.0', revision: '866c76ca80'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '14.4.1', java.version: '21.0.3'
Driver info: org.xwiki.test.ui.XWikiWebDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 125.0.2, moz:accessibilityChecks: false, moz:buildID: 20240419144423, moz:debuggerAddress: 127.0.0.1:26332, moz:firefoxOptions: {prefs: {dom.disable_beforeunload: false}}, moz:geckodriverVersion: 0.34.0, moz:headless: false, moz:platformVersion: 6.6.26-linuxkit, moz:processID: 166, moz:profile: /tmp/rust_mozprofileEOLwiq, moz:shutdownTimeout: 60000, moz:webdriverClick: true, moz:windowless: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://172.18.0.2:4444/sessio..., se:cdpVersion: 85.0, se:noVncPort: 7900, se:vnc: ws://172.18.0.2:4444/sessio..., se:vncEnabled: true, se:vncLocalAddress: ws://172.18.0.2:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: ignore, userAgent: Mozilla/5.0 (X11; Linux x86...}
Session ID: b86a5bef-5dc2-41f9-90f4-e75d49a39562
[INFO]
[ERROR] Tests run: 120, Failures: 1, Errors: 1, Skipped: 1`

**Comment by Sereza7** [comment]
Hi @tkrieck !

I could not get the error on the master branch locally, and I couldn't see it in CI (see https://ci.xwiki.org/job/XWiki%20Environment%20Tests/job/xwiki-platform/job/master/558/ ).

You need to rebuild every module where you made changes if you want to test master. Somehow it seems one of this module is failing the tests.

____
Failing test: from the log you can see that the confirm alert is not found where it should be. My guess is that it's here, but the updated DOM makes it so that it doesn't match the selector we used in the tests anymore. You probably need to find this selector and update it so that the tests do not fail anymore.

**Comment by manuelleduc** [comment]
This test is currently known to fail on master when firefox is used for the docker tests, see [GE](https://ge.xwiki.org/scans/tests?search.tags=master&search.timeZoneId=Europe%2FParis&tests.container=org.xwiki.flamingo.test.docker.AllIT$NestedObjectEditorIT&tests.test=preventUsersToLeaveTheEditorWithoutSaving&tests.unstableOnly=false#) only the builds tagged with chrome are passing.

If you want to see everything passing successfully locally, you can run `mvn clean install -Pquality,integration-tests,docker -pl :xwiki-platform-flamingo-skin-resources,:xwiki-platform-index-ui,:xwiki-platform-livedata-api,:xwiki-platform-web-templates,:xwiki-platform-flamingo-skin-test-docker -Dxwiki.test.ui.browser=chrome`. It will build every impacted modules as well as `xwiki-platform-flamingo-skin-test-docker` while using chrome.

But if it is the only failing test, I would consider that your changes are not breaking any test.

**Comment by tkrieck** [comment]
> This test is currently known to fail on master when firefox is used for the docker tests, see [GE](https://ge.xwiki.org/scans/tests?search.tags=master&search.timeZoneId=Europe%2FParis&tests.container=org.xwiki.flamingo.test.docker.AllIT$NestedObjectEditorIT&tests.test=preventUsersToLeaveTheEditorWithoutSaving&tests.unstableOnly=false#) only the builds tagged with chrome are passing.
> 
> If you want to see everything passing successfully locally, you can run `mvn clean install -Pquality,integration-tests,docker -pl :xwiki-platform-flamingo-skin-resources,:xwiki-platform-index-ui,:xwiki-platform-livedata-api,:xwiki-platform-web-templates,:xwiki-platform-flamingo-skin-test-docker -Dxwiki.test.ui.browser=chrome`. It will build every impacted modules as well as `xwiki-platform-flamingo-skin-test-docker` while using chrome.
> 
> But if it is the only failing test, I would consider that your changes are not breaking any test.

Thanks! I'll try that

**Comment by tkrieck** [comment]
I've managed to run the tests after dealing with some environment issues.

It passes with:  `mvn clean install -f xwiki-platform-core/xwiki-platform-flamingo/xwiki-platform-flamingo-skin/xwiki-platform-flamingo-skin-test/xwiki-platform-flamingo-skin-test-docker -Dxwiki.test.ui.browser=chrome  ` and `mvn clean install -Pquality,integration-tests,docker -pl :xwiki-platform-flamingo-skin-resources,:xwiki-platform-index-ui,:xwiki-platform-livedata-api,:xwiki-platform-web-templates -Dxwiki.test.ui.browser=chrome`

However, it fails when I use the command referenced by @manuelleduc on `xwiki-platform-flamingo-skin-test-docker` the others are passing. Like below:

`mvn clean install -Pquality,integration-tests,docker -pl :xwiki-platform-flamingo-skin-test-docker -Dxwiki.test.ui.browser=chrome`

The failure message is: `Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.12:check (jacoco-check) on project xwiki-platform-flamingo-skin-test-docker: Coverage checks have not been met. See log for details.`

I am unsure on how to proceed from here.

**Pull request merged**
