### PR TITLE
Stable 8.2.x When i run mvn clean install，there a checkstyle error so that the bulid progress can not be continue

### PR DESCRIPTION
**Pull request by ExtremeYu**
image
image
image
When i run mvn clean install，there a checkstyle error occurred so that the bulid progress can not be continue

Just one project called _XWiki Commons - Tools - Test Framework - Simple_ can not be passed ,so that the following project unabled to be built

### CODE REVIEW

**Comment by vmassol** [comment]
Hi @ExtremeYu 

Thanks for the pull request. However I cannot apply it since you've modified 854 files and the changes don't concern the checkstyle problem you've mentioned....

Also, I've checked out the stable-8.2.x branch and ran the build and it worked fine:

`````
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] XWiki Commons - Tools - Parent POM ................. SUCCESS [  0.864 s]
[INFO] XWiki Commons - Tools - Enforcers .................. SUCCESS [  0.256 s]
[INFO] XWiki Commons - Tools - Banned Dependencies Enforcer SUCCESS [  1.738 s]
[INFO] XWiki Commons - Tools - License Resources .......... SUCCESS [  0.289 s]
[INFO] XWiki Commons - Tools - Verification Resources ..... SUCCESS [  4.616 s]
[INFO] XWiki Commons - Tools - Test Framework - Parent POM  SUCCESS [  1.563 s]
[INFO] XWiki Commons - Tools - Test Framework - Simple .... SUCCESS [  1.734 s]
[INFO] XWiki Commons - Tools - Test Framework - Component . SUCCESS [  6.412 s]
[INFO] XWiki Commons - Tools - XAR Tools .................. SUCCESS [  0.015 s]
[INFO] XWiki Commons - Tools - XAR Tools - XAR Plugin ..... SUCCESS [  3.383 s]
[INFO] XWiki Commons - Tools - XAR Tools - XAR Handlers ... SUCCESS [  0.073 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 21.275 s
[INFO] Finished at: 2016-08-21T19:00:47+02:00
[INFO] Final Memory: 45M/517M
[INFO] ------------------------------------------------------------------------
vmassol@vmassol ~/dev/xwiki/git/xwiki-commons/xwiki-commons-tools (stable-8.2.x) $ 
`````

You can also see on our CI that it works fine:
http://ci.xwiki.org/job/xwiki-commons-8.2.x

I'm closing the PR for the moment. We can always reopen if you think there's still a problem.

Thanks!
-Vincent

**Comment by vmassol** [comment]
I wonder if the problem is related to Windows. I don't have a windows OS at hand to try it out though. Would be great if someone with windows could try it out!

**Comment by ExtremeYu** [comment]
I use Windows 10 OS,Myeslipse IDE.There two problemes,first is that the maven downloading progress is tooooooooooooooooo slow so that my workspace always show this:
image
image

**Comment by ExtremeYu** [comment]
second is that how to import the project correctly? I followed the instruction to build source,but never
 successed,

**Comment by ExtremeYu** [comment]
oh,I just want to ask for questions ,not to  merge 54 commits ,maybe i took a mistake

**Pull request closed without merging**
