### PR TITLE
XWIKI-17225: Annotation link is visible when More Action menu is removed

### PR DESCRIPTION
**Pull request by CamiAndrei**
* Dropped annotation support for older skins (Colibri)

### CODE REVIEW

**Comment by vmassol** [comment]
IMO we should not use JS but instead use a UIX. WDYT?

**Comment by mflorea** [comment]
@vmassol it already uses a UIX to inject the link in the menu, but it also needs to add a click listener from JavaScript. The issue here is that the code adding the click listener assumes the skin is Colibri if the link is missing and adds the missing link, which is wrong and @CamiAndrei PR fixes this.

**Comment by CamiAndrei** [comment]
Thank you @mflorea ! I was thinking the same .
Since 7.4M1, the annotations trigger is inserted via an UIX. 
Could this also cherry picked for 11.10.5?

**Comment by mflorea** [comment]
> Could this also cherry picked for 11.10.5?

@CamiAndrei already did.

**Comment by CamiAndrei** [comment]
Great! Thanks!

**Pull request merged**
