### PR TITLE
XWIKI-20736: Contrast issues on a themeless wiki 

### PR DESCRIPTION
**Pull request by Sereza7**
**Jira:** https://jira.xwiki.org/browse/XWIKI-20736
**PR Changes:**
* Added redefinition of some bootstrap variables when initializing a wiki without a theme.

**View:**
20736-FullScreenAfter

### CODE REVIEW

**Comment by neeraj542** [comment]
Hello everyone,
First of all, thank you for your hard work in addressing this issue. As someone who cares about accessibility, I appreciate the effort to make the themeless wiki more usable and inclusive.
After reviewing the proposed solution, I have a few suggestions. I like the idea of increasing the font size and weight for certain text elements, but I think we could also consider adjusting the line height to make the text more legible.
I would be happy to test these changes on a themeless wiki and provide feedback on how well they solve the contrast issues. If it would be helpful, I am also willing to contribute my CSS skills to help implement these changes.

Thank you again for your work on this issue, and please let me know if there is anything I can do to help.

Best regards,
Neeraj

**Comment by Sereza7** [comment]
@neeraj542 
See [this forum thread about the issue](https://forum.xwiki.org/t/fixing-a11y-contrast-issues-on-the-main-view/11917) for an in depth look at the changes. Actually all the changes here are about colors / backgrounds and there's no font size/weight changes. 
If you want to propose a change to the theme, I recommend working on the current default color theme `Flamingo>Iceberg` instead of on a themeless wiki. 
The changes here are kind of emergency patches to make our bootstrap libraries WCAG compliant even in the case there's no theme loaded (which should not be the case on many instances). The goal is to limit those changes to the minimum required and not put a whole color theme here.
It's especially useful since we just set up some WCAG validation in the functional tests (most of them run a theme-less distribution) and those contrast errors flood the warnings.

If you want to propose a change to the skin/theme, here is a recent example that you might find interesting: https://forum.xwiki.org/t/minimalist-skin-theme-design/11867

**Comment by neeraj542** [comment]
Ok, but on what type of theme should I choose in the given reference

**Comment by neeraj542** [comment]
Hello there, I am reaching out to express my interest in taking part in your organization as a GSoC contributor for this year. I am excited about the opportunity to work with your team and contribute to your projects. I believe that my skills and experience would be a good fit for your organization, and I look forward to hearing more about the projects you have in mind. Thank you for your consideration, and I hope to hear back from you soon.

**Comment by Sereza7** [comment]
@neeraj542 This discussion is about the implementation of the contrast changes, please see our forum to start a conversation and/or introduce yourself to the community: https://forum.xwiki.org/
About GSOC, I invite you to read the [XWiki Guidelines for GSOC](https://dev.xwiki.org/xwiki/bin/view/GoogleSummerOfCode/Guidelines).

**Review by vmassol — APPROVED** [review]

**Pull request merged**
