### PR TITLE
Update 10 xml file

### PR DESCRIPTION
**Pull request by Srijanjha**

### CODE REVIEW

**Comment by tmortagne** [comment]
Could you execute mvn xar:format again, there was an issue in it (https://jira.xwiki.org/browse/XCOMMONS-1326).

**Comment by Srijanjha** [comment]
Yes, I executed mvn xar: format

**Comment by tmortagne** [comment]
I know but there was a bug in the XAR plugin when you did it and it's fixed now.

**Comment by Srijanjha** [comment]
So should I redo this?

**Comment by Srijanjha** [comment]
But it will yield the same result btw.

**Comment by tmortagne** [comment]
> But it will yield the same result btw.

No, it should change the XML version in the declaration. Make sure you build with the latest version of the plugin (if you still don't see any change, try with -U to force SNAPSHOT updates).

**Comment by tmortagne** [comment]
Please use the plugin, don't modify things by hand.

**Comment by Srijanjha** [comment]
Sorry :)

**Comment by tmortagne** [comment]
I meant what you did is not what you would get with the plugin so please use it or I can't validate it.

**Comment by Srijanjha** [comment]
OK I'll try that again :)

**Pull request closed without merging**
