### PR TITLE
XWIKI-20995: AWM livetable entry sheet view uses silk icons whatever the icon theme

### PR DESCRIPTION
**Pull request by Sereza7**
## Jira
https://jira.xwiki.org/browse/XWIKI-20995
## PR Changes
* Replaced the background image LESS with displayIcon macros in the link

## View
20995-AfterPR
20955-WithSilkTheme

## Note
* I needed to change the values of the icons for it to fit into the standard set of icons supported in XWiki. I think all icons fit their purpose both on the fontawesome and silk iconthemes.

### CODE REVIEW

**Review by michitux — APPROVED** [review]
This seems to reference an attachment (`locate.png`), would it make sense to remove that or is this attachment used elsewhere?

This looks good to me, but maybe it would make sense to get some more feedback first on this UI change.

**Comment by Sereza7** [comment]
From what I could see ([github search](https://github.com/search?q=repo%3Axwiki%2Fxwiki-platform%20locate.png&type=code)), this attachment was not used anywhere else.
Fixed in https://github.com/xwiki/xwiki-platform/pull/2275/commits/84cd064fe5f38aca9753e9ab9c9c2a0aa049ecef :)

**Comment by tkrieck** [comment]
The chosen icons are good approximations of the original Silk icons, so not a problem with this IMO. Some of them are hard to decipher because of the size (translate and edit application, for example). Increasing the size could help, but carefully to not waste space.

Now on to a more conceptual view:

Different icons for the same base action is not ideal (delete, for example). And to find 100% matching icons for each of the options is very difficult.  Icons should always reinforce the base meaning of labels, but they also need to be recognized by users quickly, usually this is done using a picture that is common in other places.

If I were to redesign this section, I would group the actions between application and entries and only use icons when we can absolutely align it conceptually with the label. The other icons I would drop altogether. Showing this section as a horizontal toolbar would also help to save space.

I will make a proposal to discuss this better. Probably I am missing some implementation details and restrictions.

**Comment by michitux** [comment]
@tkrieck Not all users see all actions (depends on rights) and the text that is next to it is chosen by the user who creates the application, so this could be a longer text. I think the "Add new entry" action is the one action that should be easily available and that is frequently used while other actions should be rarely used and could thus also, e.g., be hidden in some menu.

**Comment by tkrieck** [comment]
@michitux That's nice to know, I will keep in mind on the proposal. The user can also choose the icons for these actions?

**Pull request merged**
