### PR TITLE
XWIKI-10954: "Panel Title" field is not aligned with "Create" button

### PR DESCRIPTION
**Pull request by Usamaahmad751**
**Issue**: XWIKI-10954 
**Issue link**: https://jira.xwiki.org/browse/XWIKI-10954

**Description:** Text Field and button input elements are aligned. I tested my changes on multiple browsers (Edge, Firefox, Chrome). I have solved both `Create a Job` and `Create a Panel` with a single line of code. `vertical-align: middle`.

**Before:**  

Before vertical_align
Job_before_align

**After:**

after-vertical_align

job_after_align

### CODE REVIEW

**Comment by Usamaahmad751** [comment]
> Looks good, but since this change affects many form fields, can you check other forms in XWiki to see if there are any side effects. Thanks.

To avoid any side effects on other forms I made the selectors specific to `Pane; title` and `Job name` fields. I think that's a good practice to align them without having any risk for other forms.

**Comment by mflorea** [comment]
After more thinking, I'm now more in favor of using the [``form-horizontal``](https://getbootstrap.com/docs/3.3/css/#forms-horizontal) class on the 2 forms.

**Comment by Usamaahmad751** [comment]
@mflorea I applied ` .form-horizontal` on both of these two forms but alignment is still the same without using `vertical-align`. Are you in favor of adding both class `form-horizontal` and style `vertical-align: middle` at the same time?

**Comment by mflorea** [comment]
I meant [``form-inline``](https://getbootstrap.com/docs/3.3/css/#forms-inline), sorry. But you should also:
* remove the class attribute from the input (neither ``withTip`` nor ``panelinput`` are needed anymore)
* remove the ``button`` class from the button, since it's redundant with the ``btn`` class

**Comment by Usamaahmad751** [comment]
@mflorea Please have a look at the required changes. Let me know if I have made any mistakes. Thanks

**Comment by mflorea** [comment]
Thanks for your contribution.

**Pull request merged**
