### PR TITLE
XWIKI-15898: The order of left and right panels is undeterministic

### PR DESCRIPTION
**Pull request by atallahade**
### Issue

https://jira.xwiki.org/browse/XWIKI-15898

### Changes

* Sort panels at the end of the process.

### CODE REVIEW

**Comment by surli** [comment]
It needs a test but LGTM

**Comment by atallahade** [comment]
I'll also improve the tests.

**Comment by atallahade** [comment]
@surli Could you check the new tests? I was successfully able to detect the issue that way.

**Comment by surli** [comment]
For me it's all ok.

**Pull request merged**
