### PR TITLE
XWIKI-22173: Underline the edit this page link

### PR DESCRIPTION
**Pull request by Sereza7**
# Jira URL

https://jira.xwiki.org/browse/XWIKI-22173
# Changes

## Description

* Updated the translations for the page not exist message.
* Refactored some of the style related to inline link underlining in general.less

## Clarifications

* I couldn't come up with a selector that was generic enough but not too wide to not hit unwanted links for this example. That's why I figured out it would be for the best to use the helper class `.force-underline` for this link.
* All the translations were updated. The content added does not change depending on language. I'm pretty sure we should avoid including HTML in translation values, but I don't want to refactor all of those and deprecate all of those translations. This would go further than the scope of this ticket.

# Screenshots & Video

Before the PR, Axe core detects that this inline link is not easy to detect:
22173-beforePR

after the changes in the PR, the inline link in the panel message is properly underlined, because it has the proper class:
22173-afterPR

# Executed Tests

Only manual (see test above), this is a content only change, with only an addition of a class.

# Expected merging strategy

* Prefers squash: Yes 
* Backport on branches:
  * 15.10.X like usual translation changes.
  *  16.4.X

### CODE REVIEW

**Comment by Sereza7** [comment]
Merging this would really help with reducing the number of low contrast link issues found when running WCAG tests.
Note that https://github.com/xwiki/xwiki-platform/pull/3126 earlier this week already divided the number of page tests where there was such an error by almost  3 (from 423 to 154).

With some grep I found out that it should be about half of the issues there's left:
* `grep -r "Description: Ensure links are distinguished from surrounding text in a way that does not rely on color" --after-context=8 --exclude="grepResultInlineLinks.txt"> grepResultInlineLinks.txt` in the artifact folder.
* Then search through the result file, there's 188 instances of `Description: Ensure links are distinguished from surrounding text in a way that does not rely on color` and 96 of `.panel-body > a` . 

Those numbers are approximate, but it gives a rough estimate.

**Comment by michitux** [comment]
Is there any reason why we don't want to underline links in `.panel-body` in general?

**Comment by Sereza7** [comment]
> Is there any reason why we don't want to underline links in .panel-body in general?

We discussed it sooner, and ruled the side panels out of underlining as a rule of thumb, Those side panels use the panel macro too, so ***I thought*** underlining `.panel-body` would underline them. Just checked, and they do not use this class but `.xwikipanelcontents` :/

https://www.xwiki.org/xwiki/bin/view/Documentation/DevGuide/FrontendResources/ doesn't have the Panel component, now I know why ^^' Seems like our definition of a `Panel` is not properly settled yet.

**Comment by Sereza7** [comment]
I looked a bit further, and I'd rather keep the scope of this change low. In this very panel, we have an example of a link we don't want to underline (the similar page redirection). I prefer just setting the one link that caused issues in a panel as an outlier case rather than just underline all of them. Some panels can have tables in them, so it'd also make the behaviour of links in those harder to understand.

**Pull request merged**
