### PR TITLE
XWIKI-15726: Headings hierarchy is broken when using Bootstrap .modal-title and .panel-title

### PR DESCRIPTION
**Pull request by evalica**
- Adding styling for .modal-title for the font-size property
- Replace headings usage for .modal-title and .panel-title in order to comply with WCAG rules

### CODE REVIEW

**Comment by tmortagne** [comment]
Seems much larger than export model.

**Comment by evalica** [comment]
Yeap, I also fixed the other places where we had Headings for .modal-title and .panel-title (Export was using both). Please see individual commits that I've made.

**Comment by tmortagne** [comment]
I'm fine with that, I just mean the you should probably change the issue title :)

**Comment by evalica** [comment]
I've changed the title, we should make sure when merging to Squash and change the commit title. Thanks.

**Comment by evalica** [comment]
Thank you for the review.

**Pull request merged**
