### PR TITLE
Update from Weblate.

### PR DESCRIPTION
**Pull request by xwikiorgci**

### CODE REVIEW

**Comment by vmassol** [comment]
@ldmpub This looks like a duplicate of https://github.com/xwiki/xwiki-platform/pull/953 no?

**Comment by atallahade** [comment]
@vmassol It is a duplicate yes but probably coming from a misconfiguration on l10n/weblate side. I'll investigate.

**Comment by atallahade** [comment]
I think I found the issue, it should be fixed now. Closing the PR even though we could wait for new changes to come (which would produce a rebase and thus removing the duplicates commits).

**Comment by vmassol** [comment]
Thanks @atallahade for checking and fixing!

**Pull request closed without merging**
