### PR TITLE
[Misc]: Fixing export PDF functional test

### PR DESCRIPTION
**Pull request by Sereza7**
Fixing regression introduced with https://github.com/xwiki/xwiki-platform/pull/2151
Testing logs (after PR): https://up1.xwikisas.com/#LGC2mQlGjQ5xIGzu9cUj8w

### CODE REVIEW

**Comment by michitux** [comment]
Do you have any explanation why the expected result should change?

**Comment by Sereza7** [comment]
> Do you have any explanation why the expected result should change?

The fact that the result changed is explainable: Before, because of the error in the content, the different fields were all independant. So we had Title->value for each field. However now they are all part of the same dl so I guess all values are displayed and all labels next? I'm not sure this makes sense and/or this changes anything on the display (it looks bad semantically though).

Here are the displays of the page without and with the fix from the PR. We can see that the first one lacks in structure somewhere and that the displays for both of those should be different.

miscDDinsteadOfDL
FixedDDinsteadOfDL

**Comment by Sereza7** [comment]
Here are the results of the exports (before and after PR):
[FormFieldsWithoutPR.pdf](https://github.com/xwiki/xwiki-platform/files/11323764/FormFieldsWithoutPR.pdf)
[FormFieldsWithPR.pdf](https://github.com/xwiki/xwiki-platform/files/11323763/FormFieldsWithPR.pdf)

**Comment by mflorea** [comment]
> The fact that the result changed is explainable: Before, because of the error in the content, the different fields were all independant. So we had Title->value for each field. However now they are all part of the same dl so I guess all values are displayed and all labels next? I'm not sure this makes sense and/or this changes anything on the display (it looks bad semantically though).

It has to do with:
* the way the definition list is translated into PDF (by Chrome at least)
* the way the ``PDFTextStripper`` (from pdfbox) extracts the text from the PDF page

We can't do much about it (besides providing a valid HTML of course) than checking what ``PDFTextStripper`` gives us and assuming that is the right expected text.

**Review by mflorea — APPROVED** [review]

**Pull request merged**
